//
// Copyright (c) 2016 Commercetools. All rights reserved.
//

import Foundation

/// The `Error` struct provides a convenience for creating custom Commercetools SDK NSErrors.
public struct Error {

    /// The domain used for creating all Commercetools errors.
    public static let Domain = "com.commercetools.error"

    /// The custom error codes generated by Commercetools.
    public enum Code: Int {
        case AccessTokenRetrievalFailed      = -7000
    }

    static func error(domain domain: String = Error.Domain, code: Code, failureReason: String) -> NSError {
        return error(domain: domain, code: code.rawValue, failureReason: failureReason)
    }

    static func error(domain domain: String = Error.Domain, code: Int, failureReason: String) -> NSError {
        let userInfo = [NSLocalizedFailureReasonErrorKey: failureReason]
        return NSError(domain: domain, code: code, userInfo: userInfo)
    }
}
