//
// Copyright (c) 2016 Commercetools. All rights reserved.
//

import Foundation

/// The `Error` struct provides a convenience for creating custom Commercetools SDK NSErrors.
public struct Error {

    /// The domain used for creating all Commercetools errors.
    public static let Domain = "com.commercetools.error"

    /// The custom error codes generated by Commercetools.
    public enum Code: Int {
        case ConfigurationValidationFailed   = -7000
        case AccessTokenRetrievalFailed      = -7001
    }

    static func error(domain domain: String = Error.Domain, code: Code, failureReason: String?, description: String? = nil) -> NSError {
        return error(domain: domain, code: code.rawValue, failureReason: failureReason ?? "Unknown", description: description)
    }

    static func error(domain domain: String = Error.Domain, code: Int, failureReason: String, description: String? = nil) -> NSError {
        var userInfo = [NSLocalizedFailureReasonErrorKey: failureReason]
        if let description = description {
            userInfo[NSLocalizedDescriptionKey] = description
        }
        return NSError(domain: domain, code: code, userInfo: userInfo)
    }
}
